
CREATE TABLE IF NOT EXISTS users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(256) NOT NULL UNIQUE,
    password varchar(256) NOT NULL,
    username varchar(100));

CREATE TABLE IF NOT EXIST refresh_tokens(
    user_id BIGINT REFERENCES users(id) UNIQUE ON DELETE CASCADE,
    refresh_token varchar(600) NOT NULL UNIQUE,
    primary key (user_id)
)