name: Build
on: 
  push: 
    branches: [main]

jobs:
    build:
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v3
        - name: Build
          run: cd front/ && npm i react-scripts && npm run build
        - name: Copy
          run: cp -r build/* /var/www/petbrager
        - name: nginx-restart
          run: sudo service nginx restart